import {
  Business,
  BusinessSettings,
  Outlet,
  User,
  Category,
  Brand,
  Supplier,
  Product,
  Customer,
  CashShift,
  Transaction,
  Promotion,
  Voucher,
  Notification,
  AuditLog,
  InventoryItem,
  InventoryMovement,
  Purchase,
} from '@/types';
import bcrypt from 'bcryptjs';

export const INITIAL_BUSINESS_ID = 'biz_sann_01';
export const INITIAL_OUTLET_MAIN_ID = 'out_jakarta_selatan_01';
export const INITIAL_OUTLET_BRANCH_ID = 'out_jakarta_pusat_02';

export const SEED_BUSINESS: Business = {
  id: INITIAL_BUSINESS_ID,
  name: 'Warung SANN & Mart',
  legalName: 'PT SANN Niaga Sejahtera',
  logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
  address: 'Jl. Tebet Raya No. 42, Jakarta Selatan, DKI Jakarta 12810',
  phone: '0812-9876-5432',
  email: 'halo@warungsann.com',
  taxNumber: '09.123.456.7-012.000',
  taxRate: 0.11,
  taxEnabled: true,
  currency: 'IDR',
  createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  updatedAt: new Date().toISOString(),
};

export const SEED_SETTINGS: BusinessSettings = {
  id: 'set_sann_01',
  businessId: INITIAL_BUSINESS_ID,
  receiptHeader: 'WARUNG SANN & MART\nSolusi Kebutuhan Harian & Kopi Nikmat',
  receiptFooter: 'Terima kasih atas kunjungan Anda!\nBarang yang sudah dibeli tidak dapat ditukar kecuali ada perjanjian.',
  receiptShowLogo: true,
  receiptShowCustomer: true,
  receiptShowCashier: true,
  receiptFormat: '58mm',
  autoPrintReceipt: false,
  defaultPaymentMethod: 'CASH',
  loyaltyPointsPerUnit: 10000, // Rp 10.000 = 1 Poin
  loyaltyRedeemRate: 100,      // 1 Poin = Rp 100
  minRedeemPoints: 10,
  enableSoundEffects: true,
};

export const SEED_OUTLETS: Outlet[] = [
  {
    id: INITIAL_OUTLET_MAIN_ID,
    businessId: INITIAL_BUSINESS_ID,
    name: 'Cabang Tebet (Utama)',
    code: 'TBT-01',
    address: 'Jl. Tebet Raya No. 42, Jakarta Selatan',
    phone: '0812-9876-5432',
    managerName: 'Muhammad Sann',
    isMain: true,
    isActive: true,
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: INITIAL_OUTLET_BRANCH_ID,
    businessId: INITIAL_BUSINESS_ID,
    name: 'Cabang Bendungan Hilir',
    code: 'BNH-02',
    address: 'Jl. Bendungan Hilir No. 15, Jakarta Pusat',
    phone: '0813-1122-3344',
    managerName: 'Budi Santoso',
    isMain: false,
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Pre-hashed passwords for 'password123'
const HASHED_PASSWORD_123 = '$2a$10$w09Zk.6iB6mR/p98L045E.iG21568c07802.GvJ74qZ89U6Zq1MTe';

export const SEED_USERS: (User & { passwordHash: string })[] = [
  {
    id: 'usr_owner_01',
    businessId: INITIAL_BUSINESS_ID,
    outletId: INITIAL_OUTLET_MAIN_ID,
    name: 'Muhammad Sann (Owner)',
    email: 'owner@example.com',
    phone: '0812-8888-9999',
    role: 'OWNER',
    isActive: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
    passwordHash: HASHED_PASSWORD_123,
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr_cashier_01',
    businessId: INITIAL_BUSINESS_ID,
    outletId: INITIAL_OUTLET_MAIN_ID,
    name: 'Siti Rahmawati (Kasir)',
    email: 'cashier@example.com',
    phone: '0813-7777-6666',
    role: 'CASHIER',
    isActive: true,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
    passwordHash: HASHED_PASSWORD_123,
    createdAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr_admin_01',
    businessId: INITIAL_BUSINESS_ID,
    outletId: INITIAL_OUTLET_MAIN_ID,
    name: 'Ahmad Fauzi (Supervisor)',
    email: 'admin@example.com',
    phone: '0815-4444-3333',
    role: 'ADMIN',
    isActive: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
    passwordHash: HASHED_PASSWORD_123,
    createdAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr_staff_01',
    businessId: INITIAL_BUSINESS_ID,
    outletId: INITIAL_OUTLET_MAIN_ID,
    name: 'Rudi Hartono (Gudang)',
    email: 'staff@example.com',
    phone: '0818-1234-5678',
    role: 'STAFF',
    isActive: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80',
    passwordHash: HASHED_PASSWORD_123,
    createdAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat_minuman_01',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Minuman & Kopi',
    slug: 'minuman-kopi',
    description: 'Aneka minuman dingin, kopi susu racik, teh segar, dan jus',
    icon: 'Coffee',
    color: '#0284c7',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_makanan_02',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Makanan Siap Saji',
    slug: 'makanan-siap-saji',
    description: 'Menu makanan hangat, mie instan kreasi, nasi box, dan roti bakar',
    icon: 'Utensils',
    color: '#ea580c',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_snack_03',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Snack & Camilan',
    slug: 'snack-camilan',
    description: 'Keripik gurih, biskuit, wafer, kacang, dan cokelat',
    icon: 'Cookie',
    color: '#ca8a04',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_sembako_04',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Sembako & Pokok',
    slug: 'sembako-pokok',
    description: 'Beras pilihan, minyak goreng, gula pasir, telur, dan bumbu dapur',
    icon: 'ShoppingBag',
    color: '#16a34a',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_paket_05',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Paket Hemat Combo',
    slug: 'paket-hemat-combo',
    description: 'Paket makan + minum super hemat',
    icon: 'Sparkles',
    color: '#9333ea',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_BRANDS: Brand[] = [
  { id: 'brd_sann_01', businessId: INITIAL_BUSINESS_ID, name: 'SANN Signature', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 'brd_indofood_02', businessId: INITIAL_BUSINESS_ID, name: 'Indofood', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 'brd_wings_03', businessId: INITIAL_BUSINESS_ID, name: 'Wings Food', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 'brd_mayora_04', businessId: INITIAL_BUSINESS_ID, name: 'Mayora', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 'brd_sosro_05', businessId: INITIAL_BUSINESS_ID, name: 'Sosro', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 'brd_unilever_06', businessId: INITIAL_BUSINESS_ID, name: 'Unilever', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_pangan_01',
    businessId: INITIAL_BUSINESS_ID,
    name: 'PT Sumber Pangan Nusantara',
    company: 'Sumber Pangan Nusantara',
    phone: '021-5550192',
    email: 'order@sumberpangan.co.id',
    address: 'Kawasan Industri Pulo Gadung Kav. 12, Jakarta Timur',
    notes: 'Supplier sembako, beras, dan minyak goreng. Tempo bayar 14 hari.',
    totalPurchases: 45000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sup_kopi_02',
    businessId: INITIAL_BUSINESS_ID,
    name: 'CV Jaya Roastery & Beans',
    company: 'Jaya Roastery',
    phone: '0812-3344-5566',
    email: 'sales@jayaroastery.com',
    address: 'Jl. Riau No. 88, Bandung',
    notes: 'Biji kopi Arabica & Robusta kualitas premium grade A.',
    totalPurchases: 18500000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sup_dist_03',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Distributor Sinar Makmur Jaya',
    company: 'Sinar Makmur Jaya',
    phone: '021-88997766',
    email: 'gudang@sinarmakmur.com',
    address: 'Kawasan Pergudangan Pluit Blok C No. 4, Jakarta Utara',
    notes: 'Distributor snack, minuman kemasan, dan bumbu instan.',
    totalPurchases: 32000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prd_kopi_gula_aren_01',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_minuman_01',
    brandId: 'brd_sann_01',
    supplierId: 'sup_kopi_02',
    name: 'Es Kopi Susu Gula Aren SANN',
    sku: 'SKU-KOP-001',
    barcode: '899100100101',
    description: 'Espresso house blend arabica robusta dengan susu segar creamy dan gula aren murni organik.',
    image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=400&q=80',
    costPrice: 8500,
    sellingPrice: 18000,
    wholesalePrice: 15000,
    wholesaleMinQty: 5,
    memberPrice: 16000,
    unit: 'Cup',
    minStock: 10,
    isFavorite: true,
    isActive: true,
    hasVariants: true,
    createdAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: 'var_kop_reg',
        productId: 'prd_kopi_gula_aren_01',
        name: 'Reguler (16 oz)',
        sku: 'SKU-KOP-001-REG',
        barcode: '899100100101-1',
        costPrice: 8500,
        sellingPrice: 18000,
        stock: 65,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var_kop_lrg',
        productId: 'prd_kopi_gula_aren_01',
        name: 'Large (22 oz)',
        sku: 'SKU-KOP-001-LRG',
        barcode: '899100100101-2',
        costPrice: 11000,
        sellingPrice: 23000,
        stock: 45,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var_kop_less',
        productId: 'prd_kopi_gula_aren_01',
        name: 'Less Sugar (16 oz)',
        sku: 'SKU-KOP-001-LES',
        barcode: '899100100101-3',
        costPrice: 8500,
        sellingPrice: 18000,
        stock: 50,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'prd_teh_tarik_02',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_minuman_01',
    brandId: 'brd_sann_01',
    supplierId: 'sup_dist_03',
    name: 'Es Teh Tarik Madu',
    sku: 'SKU-TEH-002',
    barcode: '899100100102',
    description: 'Teh hitam pekat wangi ditarik berbusa dengan krimer kental manis & madu lebah asli.',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=400&q=80',
    costPrice: 5000,
    sellingPrice: 14000,
    wholesalePrice: 12000,
    wholesaleMinQty: 5,
    memberPrice: 13000,
    unit: 'Cup',
    minStock: 8,
    isFavorite: true,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prd_indomie_komplit_03',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_makanan_02',
    brandId: 'brd_indofood_02',
    supplierId: 'sup_dist_03',
    name: 'Indomie Goreng Komplit SANN',
    sku: 'SKU-MIE-003',
    barcode: '899100100103',
    description: 'Indomie goreng lezat disajikan dengan telur mata sapi setengah matang, kornet tumis, caisim & taburan bawang goreng.',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80',
    costPrice: 9000,
    sellingPrice: 20000,
    wholesalePrice: 18000,
    wholesaleMinQty: 10,
    memberPrice: 18500,
    unit: 'Porsi',
    minStock: 15,
    isFavorite: true,
    isActive: true,
    hasVariants: true,
    createdAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: 'var_mie_single',
        productId: 'prd_indomie_komplit_03',
        name: 'Single + Telor',
        sku: 'SKU-MIE-003-SGL',
        barcode: '899100100103-1',
        costPrice: 7000,
        sellingPrice: 16000,
        stock: 80,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var_mie_double',
        productId: 'prd_indomie_komplit_03',
        name: 'Double + Telor + Kornet',
        sku: 'SKU-MIE-003-DBL',
        barcode: '899100100103-2',
        costPrice: 11500,
        sellingPrice: 25000,
        stock: 55,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'prd_roti_bakar_04',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_makanan_02',
    brandId: 'brd_sann_01',
    supplierId: 'sup_pangan_01',
    name: 'Roti Bakar Cokelat Keju Melt',
    sku: 'SKU-ROT-004',
    barcode: '899100100104',
    description: 'Roti gandum empuk panggang renyah dengan isian cokelat hazelnut premium dan taburan keju cheddar parut melimpah.',
    image: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=400&q=80',
    costPrice: 7500,
    sellingPrice: 17000,
    wholesalePrice: 15000,
    wholesaleMinQty: 5,
    memberPrice: 15500,
    unit: 'Porsi',
    minStock: 5,
    isFavorite: false,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prd_beras_ramos_05',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_sembako_04',
    brandId: 'brd_sann_01',
    supplierId: 'sup_pangan_01',
    name: 'Beras Ramos Super Pandan Wangi 5kg',
    sku: 'SKU-SMB-005',
    barcode: '899100100105',
    description: 'Beras putih pulen alami tanpa pemutih dan tanpa pengawet. Kualitas premium standar restoran.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    costPrice: 68000,
    sellingPrice: 78000,
    wholesalePrice: 74000,
    wholesaleMinQty: 3,
    memberPrice: 76000,
    unit: 'Sak (5kg)',
    minStock: 6,
    isFavorite: false,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prd_minyak_bimoli_06',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_sembako_04',
    brandId: 'brd_indofood_02',
    supplierId: 'sup_pangan_01',
    name: 'Minyak Goreng Bimoli Spesial Pouch 2L',
    sku: 'SKU-SMB-006',
    barcode: '899100100106',
    description: 'Minyak kelapa sawit murni kualitas keemasan jernih dengan kandungan vitamin A dan E alami.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
    costPrice: 32500,
    sellingPrice: 38500,
    wholesalePrice: 36000,
    wholesaleMinQty: 6,
    memberPrice: 37500,
    unit: 'Pouch (2L)',
    minStock: 8,
    isFavorite: true,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prd_keripik_singkong_07',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_snack_03',
    brandId: 'brd_sann_01',
    supplierId: 'sup_dist_03',
    name: 'Keripik Singkong Balado Renyah SANN',
    sku: 'SKU-SNK-007',
    barcode: '899100100107',
    description: 'Keripik singkong renyah dengan lumuran cabai merah asli bumbu balado pedas manis gurih nagih.',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80',
    costPrice: 6000,
    sellingPrice: 12000,
    wholesalePrice: 10000,
    wholesaleMinQty: 5,
    memberPrice: 11000,
    unit: 'Bungkus',
    minStock: 12,
    isFavorite: false,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 35 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prd_teh_botol_08',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_minuman_01',
    brandId: 'brd_sosro_05',
    supplierId: 'sup_dist_03',
    name: 'Teh Botol Sosro Dingin 350ml',
    sku: 'SKU-MIN-008',
    barcode: '899100100108',
    description: 'Minuman teh melati asli Indonesia segar dan wangi khas teh seduh tradisional.',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80',
    costPrice: 3800,
    sellingPrice: 6000,
    wholesalePrice: 5000,
    wholesaleMinQty: 12,
    memberPrice: 5500,
    unit: 'Botol',
    minStock: 15,
    isFavorite: true,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prd_combo_sarapan_09',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_paket_05',
    brandId: 'brd_sann_01',
    supplierId: 'sup_dist_03',
    name: 'Combo Sarapan: Kopi Susu + Roti Bakar Melt',
    sku: 'SKU-CMB-009',
    barcode: '899100100109',
    description: 'Paket sarapan nikmat: 1 Es Kopi Susu Gula Aren + 1 Roti Bakar Cokelat Keju.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=400&q=80',
    costPrice: 15000,
    sellingPrice: 30000,
    wholesalePrice: 28000,
    wholesaleMinQty: 3,
    memberPrice: 28000,
    unit: 'Paket',
    minStock: 5,
    isFavorite: true,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prd_air_mineral_10',
    businessId: INITIAL_BUSINESS_ID,
    categoryId: 'cat_minuman_01',
    brandId: 'brd_mayora_04',
    supplierId: 'sup_dist_03',
    name: 'Air Mineral Le Minerale 600ml Dingin',
    sku: 'SKU-MIN-010',
    barcode: '899100100110',
    description: 'Air mineral pegunungan alami dengan kandungan mineral seimbang, ada manis-manisnya.',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=400&q=80',
    costPrice: 2400,
    sellingPrice: 4000,
    wholesalePrice: 3200,
    wholesaleMinQty: 24,
    memberPrice: 3500,
    unit: 'Botol',
    minStock: 20,
    isFavorite: false,
    isActive: true,
    hasVariants: false,
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_INVENTORIES: InventoryItem[] = [
  { id: 'inv_01', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_kopi_gula_aren_01', quantity: 160, minStock: 15, updatedAt: new Date().toISOString() },
  { id: 'inv_02', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_teh_tarik_02', quantity: 48, minStock: 10, updatedAt: new Date().toISOString() },
  { id: 'inv_03', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_indomie_komplit_03', quantity: 135, minStock: 20, updatedAt: new Date().toISOString() },
  { id: 'inv_04', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_roti_bakar_04', quantity: 3, minStock: 10, updatedAt: new Date().toISOString() }, // LOW STOCK ALERT
  { id: 'inv_05', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_beras_ramos_05', quantity: 18, minStock: 5, updatedAt: new Date().toISOString() },
  { id: 'inv_06', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_minyak_bimoli_06', quantity: 4, minStock: 8, updatedAt: new Date().toISOString() }, // LOW STOCK ALERT
  { id: 'inv_07', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_keripik_singkong_07', quantity: 42, minStock: 10, updatedAt: new Date().toISOString() },
  { id: 'inv_08', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_teh_botol_08', quantity: 85, minStock: 15, updatedAt: new Date().toISOString() },
  { id: 'inv_09', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_combo_sarapan_09', quantity: 25, minStock: 5, updatedAt: new Date().toISOString() },
  { id: 'inv_10', outletId: INITIAL_OUTLET_MAIN_ID, productId: 'prd_air_mineral_10', quantity: 120, minStock: 20, updatedAt: new Date().toISOString() },

  // Branch inventories
  { id: 'inv_b_01', outletId: INITIAL_OUTLET_BRANCH_ID, productId: 'prd_kopi_gula_aren_01', quantity: 80, minStock: 10, updatedAt: new Date().toISOString() },
  { id: 'inv_b_02', outletId: INITIAL_OUTLET_BRANCH_ID, productId: 'prd_teh_tarik_02', quantity: 30, minStock: 10, updatedAt: new Date().toISOString() },
  { id: 'inv_b_03', outletId: INITIAL_OUTLET_BRANCH_ID, productId: 'prd_indomie_komplit_03', quantity: 60, minStock: 15, updatedAt: new Date().toISOString() },
  { id: 'inv_b_04', outletId: INITIAL_OUTLET_BRANCH_ID, productId: 'prd_roti_bakar_04', quantity: 12, minStock: 5, updatedAt: new Date().toISOString() },
  { id: 'inv_b_05', outletId: INITIAL_OUTLET_BRANCH_ID, productId: 'prd_beras_ramos_05', quantity: 10, minStock: 5, updatedAt: new Date().toISOString() },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cst_hendra_01',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Hendra Wijaya',
    phone: '0812-9911-2233',
    email: 'hendra.wijaya@gmail.com',
    address: 'Apartemen Sudirman Park Tower B No. 1204',
    birthday: '1990-05-14',
    notes: 'Pelanggan langganan Kopi Gula Aren pagi hari',
    totalSpend: 1450000,
    totalVisits: 28,
    points: 145,
    tier: 'GOLD',
    createdAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cst_anisa_02',
    businessId: INITIAL_BUSINESS_ID,
    name: 'dr. Anisa Putri',
    phone: '0813-8822-4455',
    email: 'anisa.putri@klinik.co.id',
    address: 'Jl. Casablanca No. 88, Jakarta Selatan',
    birthday: '1994-11-20',
    notes: 'Sering pesan paket sarapan untuk staf klinik',
    totalSpend: 820000,
    totalVisits: 14,
    points: 82,
    tier: 'SILVER',
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cst_rezky_03',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Rezky Pratama',
    phone: '0857-1122-3399',
    email: 'rezky.p@startup.id',
    address: 'Tebet Timur Dalam VII No. 3',
    birthday: '1998-03-08',
    notes: 'Suka Indomie Double Kornet Telor',
    totalSpend: 390000,
    totalVisits: 8,
    points: 39,
    tier: 'BRONZE',
    createdAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_VOUCHERS: Voucher[] = [
  {
    id: 'vch_diskon10',
    businessId: INITIAL_BUSINESS_ID,
    code: 'DISKON10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minSpend: 30000,
    maxDiscount: 15000,
    usageLimit: 500,
    usedCount: 42,
    startDate: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    endDate: new Date(Date.now() + 60 * 24 * 3600 * 1000).toISOString(),
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vch_hemat20k',
    businessId: INITIAL_BUSINESS_ID,
    code: 'HEMAT20K',
    discountType: 'FIXED',
    discountValue: 20000,
    minSpend: 100000,
    maxDiscount: 20000,
    usageLimit: 200,
    usedCount: 18,
    startDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString(),
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vch_pelangganbaru',
    businessId: INITIAL_BUSINESS_ID,
    code: 'WARUNGBARU',
    discountType: 'PERCENTAGE',
    discountValue: 15,
    minSpend: 20000,
    maxDiscount: 10000,
    usageLimit: 100,
    usedCount: 9,
    startDate: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    endDate: new Date(Date.now() + 45 * 24 * 3600 * 1000).toISOString(),
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_PROMOTIONS: Promotion[] = [
  {
    id: 'prm_jumat_berkah',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Jumat Berkah Diskon 10%',
    type: 'PERCENTAGE_DISCOUNT',
    value: 10,
    minSpend: 25000,
    startDate: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    endDate: new Date(Date.now() + 60 * 24 * 3600 * 1000).toISOString(),
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prm_beli2gratis1',
    businessId: INITIAL_BUSINESS_ID,
    name: 'Buy 2 Get 1 Free Keripik Balado',
    type: 'BUY_X_GET_Y',
    value: 12000,
    minSpend: 24000,
    startDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString(),
    isActive: true,
    rulesJson: JSON.stringify({ buyQty: 2, getQty: 1, targetProductId: 'prd_keripik_singkong_07' }),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_ACTIVE_SHIFT: CashShift = {
  id: 'shf_active_01',
  registerId: 'reg_pos_01',
  outletId: INITIAL_OUTLET_MAIN_ID,
  userId: 'usr_cashier_01',
  userName: 'Siti Rahmawati (Kasir)',
  status: 'OPEN',
  openingCash: 250000,
  cashSales: 645000,
  nonCashSales: 412000,
  cashInTotal: 0,
  cashOutTotal: 25000, // beli plastik & es batu
  openedAt: new Date(new Date().setHours(7, 30, 0, 0)).toISOString(),
};

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_01',
    outletId: INITIAL_OUTLET_MAIN_ID,
    title: 'Peringatan Stok Kritis!',
    message: 'Stok Roti Bakar Cokelat Keju sisa 3 porsi (Batas minimum: 10 porsi). Segera lakukan pemesanan ke supplier!',
    type: 'LOW_STOCK',
    isRead: false,
    linkUrl: '/inventory',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif_02',
    outletId: INITIAL_OUTLET_MAIN_ID,
    title: 'Stok Menipis',
    message: 'Minyak Goreng Bimoli 2L tinggal 4 pouch di Cabang Tebet.',
    type: 'LOW_STOCK',
    isRead: false,
    linkUrl: '/inventory',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif_03',
    outletId: INITIAL_OUTLET_MAIN_ID,
    title: 'Shift Kasir Dibuka',
    message: 'Siti Rahmawati membuka shift kasir dengan modal awal Rp 250.000.',
    type: 'SYSTEM',
    isRead: true,
    linkUrl: '/shifts',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_01',
    businessId: INITIAL_BUSINESS_ID,
    userId: 'usr_owner_01',
    userName: 'Muhammad Sann',
    userRole: 'OWNER',
    action: 'LOGIN',
    entity: 'User',
    entityId: 'usr_owner_01',
    metadata: JSON.stringify({ device: 'Desktop Chrome Windows', ip: '180.252.14.9' }),
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'aud_02',
    businessId: INITIAL_BUSINESS_ID,
    userId: 'usr_cashier_01',
    userName: 'Siti Rahmawati',
    userRole: 'CASHIER',
    action: 'SHIFT_OPEN',
    entity: 'CashShift',
    entityId: 'shf_active_01',
    metadata: JSON.stringify({ openingCash: 250000, outlet: 'Cabang Tebet' }),
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
];

export const SEED_PURCHASES: Purchase[] = [
  {
    id: 'po_sann_01',
    poNumber: 'PO-2026-08-001',
    outletId: INITIAL_OUTLET_MAIN_ID,
    supplierId: 'sup_kopi_02',
    supplierName: 'CV Jaya Roastery & Beans',
    createdById: 'usr_owner_01',
    createdByName: 'Muhammad Sann',
    status: 'RECEIVED',
    subtotal: 3500000,
    taxAmount: 0,
    discountAmount: 100000,
    grandTotal: 3400000,
    notes: 'Pemesanan biji kopi House Blend 25kg & Gula Aren 20kg',
    orderedAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    receivedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    items: [
      {
        id: 'poi_01',
        purchaseId: 'po_sann_01',
        productId: 'prd_kopi_gula_aren_01',
        productName: 'Biji Kopi House Blend Arabica Robusta',
        quantity: 50,
        unitCost: 70000,
        subtotal: 3500000,
      },
    ],
  },
  {
    id: 'po_sann_02',
    poNumber: 'PO-2026-08-002',
    outletId: INITIAL_OUTLET_MAIN_ID,
    supplierId: 'sup_pangan_01',
    supplierName: 'PT Sumber Pangan Nusantara',
    createdById: 'usr_staff_01',
    createdByName: 'Rudi Hartono',
    status: 'ORDERED',
    subtotal: 5800000,
    taxAmount: 0,
    discountAmount: 0,
    grandTotal: 5800000,
    notes: 'Restock beras 50 sak dan minyak goreng 40 pouch',
    orderedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: 'poi_02',
        purchaseId: 'po_sann_02',
        productId: 'prd_beras_ramos_05',
        productName: 'Beras Ramos Super 5kg',
        quantity: 50,
        unitCost: 68000,
        subtotal: 3400000,
      },
      {
        id: 'poi_03',
        purchaseId: 'po_sann_02',
        productId: 'prd_minyak_bimoli_06',
        productName: 'Minyak Goreng Bimoli 2L',
        quantity: 70,
        unitCost: 32500,
        subtotal: 2275000,
      },
    ],
  },
];

// Generate past 7 days realistic transactions
export function generateSeedTransactions(): Transaction[] {
  const transactions: Transaction[] = [];
  const now = Date.now();

  const mockPurchases = [
    {
      cust: SEED_CUSTOMERS[0],
      items: [
        { product: SEED_PRODUCTS[0], qty: 2, price: 18000, cost: 8500, varName: 'Reguler (16 oz)' },
        { product: SEED_PRODUCTS[2], qty: 1, price: 20000, cost: 9000, varName: 'Single + Telor' },
      ],
      payment: 'QRIS' as const,
    },
    {
      cust: SEED_CUSTOMERS[1],
      items: [
        { product: SEED_PRODUCTS[8], qty: 3, price: 30000, cost: 15000, varName: null },
      ],
      payment: 'BANK_TRANSFER' as const,
    },
    {
      cust: null,
      items: [
        { product: SEED_PRODUCTS[1], qty: 1, price: 14000, cost: 5000, varName: null },
        { product: SEED_PRODUCTS[6], qty: 2, price: 12000, cost: 6000, varName: null },
      ],
      payment: 'CASH' as const,
    },
    {
      cust: SEED_CUSTOMERS[2],
      items: [
        { product: SEED_PRODUCTS[2], qty: 2, price: 25000, cost: 11500, varName: 'Double + Telor + Kornet' },
        { product: SEED_PRODUCTS[7], qty: 2, price: 6000, cost: 3800, varName: null },
      ],
      payment: 'E_WALLET' as const,
    },
    {
      cust: null,
      items: [
        { product: SEED_PRODUCTS[4], qty: 1, price: 78000, cost: 68000, varName: null },
        { product: SEED_PRODUCTS[5], qty: 1, price: 38500, cost: 32500, varName: null },
      ],
      payment: 'DEBIT_CARD' as const,
    },
  ];

  for (let i = 0; i < 24; i++) {
    const daysAgo = Math.floor(i / 4);
    const hoursAgo = (i % 4) * 3 + Math.floor(Math.random() * 2);
    const date = new Date(now - daysAgo * 24 * 3600 * 1000 - hoursAgo * 3600 * 1000);
    const template = mockPurchases[i % mockPurchases.length];

    let subtotal = 0;
    let totalCost = 0;
    const txItems = template.items.map((it, idx) => {
      const lineSubtotal = it.price * it.qty;
      const lineCost = it.cost * it.qty;
      subtotal += lineSubtotal;
      totalCost += lineCost;

      return {
        id: `txi_${i}_${idx}`,
        transactionId: `tx_sann_${1000 + i}`,
        productId: it.product.id,
        variantId: null,
        productName: it.product.name,
        variantName: it.varName,
        sku: it.product.sku,
        quantity: it.qty,
        unitCost: it.cost,
        unitPrice: it.price,
        discount: 0,
        subtotal: lineSubtotal,
        profit: lineSubtotal - lineCost,
        notes: null,
      };
    });

    const taxAmount = Math.round(subtotal * 0.11);
    const grandTotal = subtotal + taxAmount;
    const grossProfit = subtotal - totalCost;

    const tx: Transaction = {
      id: `tx_sann_${1000 + i}`,
      invoiceNumber: `INV/${date.getFullYear()}${(date.getMonth() + 1).toString().padStart(2, '0')}${date.getDate().toString().padStart(2, '0')}/${(1000 + i).toString()}`,
      outletId: INITIAL_OUTLET_MAIN_ID,
      cashierId: 'usr_cashier_01',
      cashierName: 'Siti Rahmawati (Kasir)',
      customerId: template.cust?.id || null,
      customerName: template.cust?.name || 'Pelanggan Umum (Guest)',
      customerPhone: template.cust?.phone || null,
      subtotal,
      itemDiscountTotal: 0,
      orderDiscountTotal: 0,
      voucherCode: null,
      voucherDiscount: 0,
      taxAmount,
      taxRate: 0.11,
      grandTotal,
      totalCost,
      grossProfit,
      pointsEarned: Math.floor(subtotal / 10000),
      pointsRedeemed: 0,
      pointsDiscount: 0,
      status: 'COMPLETED',
      shiftId: 'shf_active_01',
      createdAt: date.toISOString(),
      updatedAt: date.toISOString(),
      items: txItems,
      payments: [
        {
          id: `pay_${i}`,
          transactionId: `tx_sann_${1000 + i}`,
          method: template.payment,
          amount: grandTotal,
          amountPaid: template.payment === 'CASH' ? Math.ceil(grandTotal / 50000) * 50000 : grandTotal,
          change: template.payment === 'CASH' ? Math.ceil(grandTotal / 50000) * 50000 - grandTotal : 0,
          reference: template.payment === 'QRIS' ? `QRIS-NMID-${100000 + i}` : null,
          status: 'SUCCESS',
          createdAt: date.toISOString(),
        },
      ],
    };

    transactions.push(tx);
  }

  return transactions;
}
